[package]
name = "risc0-zeroio"
description = "RISC Zero zero-copy deserialization"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[dependencies]
bytemuck = "1.12"
impl-trait-for-tuples = "0.2"
log = "0.4"
risc0-zeroio-derive = { workspace = true }
risc0-zkvm-platform = { workspace = true }
tracing = { version = "0.1", default-features = false, features = ["attributes"] }

[target.'cfg(not(target_os = "zkvm"))'.dev-dependencies]
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
test-log = { version = "0.2", features = ["trace"] }
env_logger = "0.10"

[features]
default = ["std"]
std = []
# Enabling the "debug-derive" feature will allow errors in generated
# code to be reported in context by writing out the generated code to
# an external file and then using the "include" macro as opposed to
# emitting it inline.
#
# Warning: Enabling this feature will litter your source tree with
# generated files.
debug-derive = ["risc0-zeroio-derive/debug-derive"]
