[package]
name = "risc0-zkp"
description = "RISC Zero zero-knowledge proof system core crate"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }

[[bench]]
name = "ntt"
harness = false

[dependencies]
anyhow = { version = "1.0", default-features = false }
bytemuck = { version = "1.12", features = ["derive"] }
digest = "0.10"
fil-rustacuda = { version = "0.1", optional = true }
hex = { version = "0.4.3", default-features = false, features = ["alloc"] }
metal = { version = "0.24", optional = true }
paste = "1.0"
rand_core = "0.6"
risc0-core = { workspace = true }
risc0-sys = { workspace = true, optional = true }
risc0-zeroio = { workspace = true }
risc0-zkvm-platform = { workspace = true }
rustacuda_core = { version = "0.1", optional = true }
rustacuda_derive = { version = "0.1", optional = true }
serde = { version = "1.0", default-features = false, features = ["derive"] }
tracing = { version = "0.1", default-features = false, features = ["attributes"] }

[target.'cfg(not(target_os = "zkvm"))'.dependencies]
log = "0.4"
ndarray = { version = "0.15", features = ["rayon"], optional = true }
rand = { version = "0.8", optional = true }
rayon = { version = "1.5", optional = true }
sha2 = { version = "0.10", default-features = false, features = ["compress"] }

[dev-dependencies]
criterion = "0.4"
env_logger = "0.10"
rand = { version = "0.8", features = ["small_rng"] }
serial_test = "1.0"
test-log = "0.2"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[features]
default = ["prove"]
cuda = ["dep:fil-rustacuda", "dep:rustacuda_core", "dep:rustacuda_derive", "risc0-sys/cuda"]
metal = ["dep:metal", "risc0-sys/metal"]
prove = [
    "dep:ndarray",
    "dep:rand",
    "dep:rayon",
    "std",
    "risc0-sys"
]
std = ["anyhow/std", "risc0-zeroio/std"]
